// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9rQdnUQ_MZdIii5ps2WqYq85RSBpGog',
    appId: '1:997042148663:web:acc5eef374224b7cc1b6b2',
    messagingSenderId: '997042148663',
    projectId: 'flutter-firebase-login-51335',
    authDomain: 'flutter-firebase-login-51335.firebaseapp.com',
    storageBucket: 'flutter-firebase-login-51335.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk7EqV60hcIEeDOeK5DfzHJq3_u90mzjc',
    appId: '1:997042148663:android:dbc07fb1eadd4409c1b6b2',
    messagingSenderId: '997042148663',
    projectId: 'flutter-firebase-login-51335',
    storageBucket: 'flutter-firebase-login-51335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYX7S_Ar4i2BfoAhdUzByFeHXNDuQIHeQ',
    appId: '1:997042148663:ios:c485f8e8affbbb30c1b6b2',
    messagingSenderId: '997042148663',
    projectId: 'flutter-firebase-login-51335',
    storageBucket: 'flutter-firebase-login-51335.appspot.com',
    iosClientId: '997042148663-9geeovu25ctj1ulc7v251iub25obem3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYX7S_Ar4i2BfoAhdUzByFeHXNDuQIHeQ',
    appId: '1:997042148663:ios:c485f8e8affbbb30c1b6b2',
    messagingSenderId: '997042148663',
    projectId: 'flutter-firebase-login-51335',
    storageBucket: 'flutter-firebase-login-51335.appspot.com',
    iosClientId: '997042148663-9geeovu25ctj1ulc7v251iub25obem3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
